# Generated by Django 4.2.5 on 2023-12-12 08:19

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('from_email', models.EmailField(max_length=254, verbose_name='Sender')),
                ('to_email', models.EmailField(max_length=254, verbose_name='Recipient')),
                ('reply_to', models.EmailField(max_length=254, verbose_name='Replied to')),
                ('subject', models.CharField(max_length=250, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Email body')),
                ('sent_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Sent date and time')),
                ('status', models.CharField(choices=[('created', 'Email is created'), ('processing', 'Sending process'), ('sent', 'Email is sent'), ('failed', 'Email is not sent')], default='created', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ('from_email', 'to_email'),
            },
        ),
    ]
