# Generated by Django 4.2.5 on 2023-11-28 15:33

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='_status',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller'), ('buyer', 'Buyer')], default='admin', max_length=20, verbose_name='User status'),
        ),
    ]
