# Generated by Django 4.2.5 on 2023-12-10 09:14

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('visible', models.BooleanField(default=True, verbose_name='Visibility status')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('code', models.CharField(max_length=30, verbose_name='PromoCode')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promos', to=settings.AUTH_USER_MODEL, verbose_name='Owner of the promotion')),
            ],
            options={
                'verbose_name': 'Promo',
                'verbose_name_plural': 'Promos',
                'ordering': ('name',),
            },
        ),
    ]
