# Generated by Django 4.2.5 on 2023-12-11 05:43

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promos',
            field=models.JSONField(blank=True, null=True, verbose_name='Promos used in order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.JSONField(default=[], verbose_name='Ordered products'),
            preserve_default=False,
        ),
    ]
