# Generated by Django 4.2.5 on 2023-12-11 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_promos_alter_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='buyer',
            new_name='owner',
        ),
    ]
