# Generated by Django 4.2.5 on 2024-01-11 08:24

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneralData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=20, null=True, verbose_name="Marketplace's contact email address."
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Marketplace's contact phone number."
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Marketplace's contact telegram link."
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketplace general data, site settings",
                "verbose_name_plural": "Marketplace general data, site settings",
            },
        ),
    ]
